<?php

use Drupal\Core\Routing\RouteMatchInterface;

function empresa_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'empresa_simple':
      	return t('This is help text for the simple page.');
    case 'help.page.page_example':
    	return t("This is help text created in page example's implementation of hook_help().");
  }
}

/**
 * Theme hook
 */
function empresa_theme($theme, $title, $description, $comments, $rows) {
  return array('empresa' =>
    array(
      'variables' => array(
        'rows'        => null, 
        'description' => null,
        'title'       => '',
        'comments'    => '',
      ),
      'template' => 'empresa'
    )
  );
}